export const timeZoneList = [{"country":"Afghanistan", "short":"AF", "long":"Afghanistan Standard Time", "value":"(UTC+04:30)", "cities":"Kabul"},
        {"country":"Åland Islands", "short":"AX", "long":"FLE Standard Time", "value":"(UTC+02:00)", "cities":"Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius"},
        {"country":"Albania", "short":"AL", "long":"Central Europe Standard Time", "value":"(UTC+01:00)", "cities":"Belgrade, Bratislava, Budapest, Ljubljana, Prague"},
        {"country":"Algeria", "short":"DZ", "long":"W. Central Africa Standard Time", "value":"(UTC+01:00)", "cities":"West Central Africa"},
        {"country":"American Samoa", "short":"AS", "long":"UTC-11", "value":"(UTC-11:00)", "cities":"Coordinated Universal Time-11"},
        {"country":"Andorra", "short":"AD", "long":"W. Europe Standard Time", "value":"(UTC+01:00)", "cities":"Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna"},
        {"country":"Angola", "short":"AO", "long":"W. Central Africa Standard Time", "value":"(UTC+01:00)", "cities":"West Central Africa"},
        {"country":"Anguilla", "short":"AI", "long":"SA Western Standard Time", "value":"(UTC-04:00)", "cities":"Georgetown, La Paz, Manaus, San Juan"},
        {"country":"Antarctica", "short":"AQ", "long":"Pacific SA Standard Time", "value":"(UTC-03:00)", "cities":"Santiago"},
        {"country":"Antigua and Barbuda", "short":"AG", "long":"SA Western Standard Time", "value":"(UTC-04:00)", "cities":"Georgetown, La Paz, Manaus, San Juan"},
        {"country":"Argentina", "short":"AR", "long":"Argentina Standard Time", "value":"(UTC-03:00)", "cities":"City of Buenos Aires"},
        {"country":"Armenia", "short":"AM", "long":"Caucasus Standard Time", "value":"(UTC+04:00)", "cities":"Yerevan"},
        {"country":"Aruba", "short":"AW", "long":"SA Western Standard Time", "value":"(UTC-04:00)", "cities":"Georgetown, La Paz, Manaus, San Juan"},
        {"country":"Australia", "short":"AU", "long":"AUS Eastern Standard Time", "value":"(UTC+10:00)", "cities":"Canberra, Melbourne, Sydney"},
        {"country":"Austria", "short":"AT", "long":"W. Europe Standard Time", "value":"(UTC+01:00)", "cities":"Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna"},
        {"country":"Azerbaijan", "short":"AZ", "long":"Azerbaijan Standard Time", "value":"(UTC+04:00)", "cities":"Baku"},
        {"country":"Bahamas, The", "short":"BS", "long":"Eastern Standard Time", "value":"(UTC-05:00)", "cities":"Eastern Time (US & Canada)"},
        {"country":"Bahrain", "short":"BH", "long":"Arab Standard Time", "value":"(UTC+03:00)", "cities":"Kuwait, Riyadh"},
        {"country":"Bangladesh", "short":"BD", "long":"Bangladesh Standard Time", "value":"(UTC+06:00)", "cities":"Dhaka"},
        {"country":"Barbados", "short":"BB", "long":"SA Western Standard Time", "value":"(UTC-04:00)", "cities":"Georgetown, La Paz, Manaus, San Juan"},
        {"country":"Belarus", "short":"BY", "long":"Belarus Standard Time", "value":"(UTC+03:00)", "cities":"Minsk"},
        {"country":"Belgium", "short":"BE", "long":"Romance Standard Time", "value":"(UTC+01:00)", "cities":"Brussels, Copenhagen, Madrid, Paris"},
        {"country":"Belize", "short":"BZ", "long":"Central America Standard Time", "value":"(UTC-06:00)", "cities":"Central America"},
        {"country":"Benin", "short":"BJ", "long":"W. Central Africa Standard Time", "value":"(UTC+01:00)", "cities":"West Central Africa"},
        {"country":"Bermuda", "short":"BM", "long":"Atlantic Standard Time", "value":"(UTC-04:00)", "cities":"Atlantic Time (Canada)"},
        {"country":"Bhutan", "short":"BT", "long":"Bangladesh Standard Time", "value":"(UTC+06:00)", "cities":"Dhaka"},
        {"country":"Bolivarian Republic of Venezuela", "short":"VE", "long":"Venezuela Standard Time", "value":"(UTC-04:30)", "cities":"Caracas"},
        {"country":"Bolivia", "short":"BO", "long":"SA Western Standard Time", "value":"(UTC-04:00)", "cities":"Georgetown, La Paz, Manaus, San Juan"},
        {"country":"Bonaire, Sint Eustatius and Saba", "short":"BQ", "long":"SA Western Standard Time", "value":"(UTC-04:00)", "cities":"Georgetown, La Paz, Manaus, San Juan"},
        {"country":"Bosnia and Herzegovina", "short":"BA", "long":"Central European Standard Time", "value":"(UTC+01:00)", "cities":"Sarajevo, Skopje, Warsaw, Zagreb"},
        {"country":"Botswana", "short":"BW", "long":"South Africa Standard Time", "value":"(UTC+02:00)", "cities":"Harare, Pretoria"},
        {"country":"Bouvet Island", "short":"BV", "long":"UTC", "value":"(UTC)", "cities":"Coordinated Universal Time"},
        {"country":"Brazil", "short":"BR", "long":"E. South America Standard Time", "value":"(UTC-03:00)", "cities":"Brasilia"},
        {"country":"British Indian Ocean Territory", "short":"IO", "long":"Central Asia Standard Time", "value":"(UTC+06:00)", "cities":"Astana"},
        {"country":"Brunei", "short":"BN", "long":"Singapore Standard Time", "value":"(UTC+08:00)", "cities":"Kuala Lumpur, Singapore"},
        {"country":"Bulgaria", "short":"BG", "long":"FLE Standard Time", "value":"(UTC+02:00)", "cities":"Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius"},
        {"country":"Burkina Faso", "short":"BF", "long":"Greenwich Standard Time", "value":"(UTC)", "cities":"Monrovia, Reykjavik"},
        {"country":"Burundi", "short":"BI", "long":"South Africa Standard Time", "value":"(UTC+02:00)", "cities":"Harare, Pretoria"},
        {"country":"Cabo Verde", "short":"CV", "long":"Cape Verde Standard Time", "value":"(UTC-01:00)", "cities":"Cabo Verde Is."},
        {"country":"Cambodia", "short":"KH", "long":"SE Asia Standard Time", "value":"(UTC+07:00)", "cities":"Bangkok, Hanoi, Jakarta"},
        {"country":"Cameroon", "short":"CM", "long":"W. Central Africa Standard Time", "value":"(UTC+01:00)", "cities":"West Central Africa"},
        {"country":"Canada", "short":"CA", "long":"Eastern Standard Time", "value":"(UTC-05:00)", "cities":"Eastern Time (US & Canada)"},
        {"country":"Cayman Islands", "short":"KY", "long":"SA Pacific Standard Time", "value":"(UTC-05:00)", "cities":"Bogota, Lima, Quito, Rio Branco"},
        {"country":"Central African Republic", "short":"CF", "long":"W. Central Africa Standard Time", "value":"(UTC+01:00)", "cities":"West Central Africa"},
        {"country":"Chad", "short":"TD", "long":"W. Central Africa Standard Time", "value":"(UTC+01:00)", "cities":"West Central Africa"},
        {"country":"Chile", "short":"CL", "long":"Pacific SA Standard Time", "value":"(UTC-03:00)", "cities":"Santiago"},
        {"country":"China", "short":"CN", "long":"China Standard Time", "value":"(UTC+08:00)", "cities":"Beijing, Chongqing, Hong Kong SAR, Urumqi"},
        {"country":"Christmas Island", "short":"CX", "long":"SE Asia Standard Time", "value":"(UTC+07:00)", "cities":"Bangkok, Hanoi, Jakarta"},
        {"country":"Cocos (Keeling) Islands", "short":"CC", "long":"Myanmar Standard Time", "value":"(UTC+06:30)", "cities":"Yangon (Rangoon)"},
        {"country":"Colombia", "short":"CO", "long":"SA Pacific Standard Time", "value":"(UTC-05:00)", "cities":"Bogota, Lima, Quito, Rio Branco"},
        {"country":"Comoros", "short":"KM", "long":"E. Africa Standard Time", "value":"(UTC+03:00)", "cities":"Nairobi"},
        {"country":"Congo", "short":"CG", "long":"W. Central Africa Standard Time", "value":"(UTC+01:00)", "cities":"West Central Africa"},
        {"country":"Congo (DRC)", "short":"CD", "long":"W. Central Africa Standard Time", "value":"(UTC+01:00)", "cities":"West Central Africa"},
        {"country":"Cook Islands", "short":"CK", "long":"Hawaiian Standard Time", "value":"(UTC-10:00)", "cities":"Hawaii"},
        {"country":"Costa Rica", "short":"CR", "long":"Central America Standard Time", "value":"(UTC-06:00)", "cities":"Central America"},
        {"country":"Côte d'Ivoire", "short":"CI", "long":"Greenwich Standard Time", "value":"(UTC)", "cities":"Monrovia, Reykjavik"},
        {"country":"Croatia", "short":"HR", "long":"Central European Standard Time", "value":"(UTC+01:00)", "cities":"Sarajevo, Skopje, Warsaw, Zagreb"},
        {"country":"Cuba", "short":"CU", "long":"Eastern Standard Time", "value":"(UTC-05:00)", "cities":"Eastern Time (US & Canada)"},
        {"country":"Curaçao", "short":"CW", "long":"SA Western Standard Time", "value":"(UTC-04:00)", "cities":"Georgetown, La Paz, Manaus, San Juan"},
        {"country":"Cyprus", "short":"CY", "long":"E. Europe Standard Time", "value":"(UTC+02:00)", "cities":"E. Europe"},
        {"country":"Czech Republic", "short":"CZ", "long":"Central Europe Standard Time", "value":"(UTC+01:00)", "cities":"Belgrade, Bratislava, Budapest, Ljubljana, Prague"},
        {"country":"Democratic Republic of Timor-Leste", "short":"TL", "long":"Tokyo Standard Time", "value":"(UTC+09:00)", "cities":"Osaka, Sapporo, Tokyo"},
        {"country":"Denmark", "short":"DK", "long":"Romance Standard Time", "value":"(UTC+01:00)", "cities":"Brussels, Copenhagen, Madrid, Paris"},
        {"country":"Djibouti", "short":"DJ", "long":"E. Africa Standard Time", "value":"(UTC+03:00)", "cities":"Nairobi"},
        {"country":"Dominica", "short":"DM", "long":"SA Western Standard Time", "value":"(UTC-04:00)", "cities":"Georgetown, La Paz, Manaus, San Juan"},
        {"country":"Dominican Republic", "short":"DO", "long":"SA Western Standard Time", "value":"(UTC-04:00)", "cities":"Georgetown, La Paz, Manaus, San Juan"},
        {"country":"Ecuador", "short":"EC", "long":"SA Pacific Standard Time", "value":"(UTC-05:00)", "cities":"Bogota, Lima, Quito, Rio Branco"},
        {"country":"Egypt", "short":"EG", "long":"Egypt Standard Time", "value":"(UTC+02:00)", "cities":"Cairo"},
        {"country":"El Salvador", "short":"SV", "long":"Central America Standard Time", "value":"(UTC-06:00)", "cities":"Central America"},
        {"country":"Equatorial Guinea", "short":"GQ", "long":"W. Central Africa Standard Time", "value":"(UTC+01:00)", "cities":"West Central Africa"},
        {"country":"Eritrea", "short":"ER", "long":"E. Africa Standard Time", "value":"(UTC+03:00)", "cities":"Nairobi"},
        {"country":"Estonia", "short":"EE", "long":"FLE Standard Time", "value":"(UTC+02:00)", "cities":"Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius"},
        {"country":"Ethiopia", "short":"ET", "long":"E. Africa Standard Time", "value":"(UTC+03:00)", "cities":"Nairobi"},
        {"country":"Falkland Islands (Islas Malvinas)", "short":"FK", "long":"SA Eastern Standard Time", "value":"(UTC-03:00)", "cities":"Cayenne, Fortaleza"},
        {"country":"Faroe Islands", "short":"FO", "long":"GMT Standard Time", "value":"(UTC)", "cities":"Dublin, Edinburgh, Lisbon, London"},
        {"country":"Fiji Islands", "short":"FJ", "long":"Fiji Standard Time", "value":"(UTC+12:00)", "cities":"Fiji"},
        {"country":"Finland", "short":"FI", "long":"FLE Standard Time", "value":"(UTC+02:00)", "cities":"Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius"},
        {"country":"France", "short":"FR", "long":"Romance Standard Time", "value":"(UTC+01:00)", "cities":"Brussels, Copenhagen, Madrid, Paris"},
        {"country":"French Guiana", "short":"GF", "long":"SA Eastern Standard Time", "value":"(UTC-03:00)", "cities":"Cayenne, Fortaleza"},
        {"country":"French Polynesia", "short":"PF", "long":"Hawaiian Standard Time", "value":"(UTC-10:00)", "cities":"Hawaii"},
        {"country":"French Southern and Antarctic Lands", "short":"TF", "long":"West Asia Standard Time", "value":"(UTC+05:00)", "cities":"Ashgabat, Tashkent"},
        {"country":"Gabon", "short":"GA", "long":"W. Central Africa Standard Time", "value":"(UTC+01:00)", "cities":"West Central Africa"},
        {"country":"Gambia, The", "short":"GM", "long":"Greenwich Standard Time", "value":"(UTC)", "cities":"Monrovia, Reykjavik"},
        {"country":"Georgia", "short":"GE", "long":"Georgian Standard Time", "value":"(UTC+04:00)", "cities":"Tbilisi"},
        {"country":"Germany", "short":"DE", "long":"W. Europe Standard Time", "value":"(UTC+01:00)", "cities":"Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna"},
        {"country":"Ghana", "short":"GH", "long":"Greenwich Standard Time", "value":"(UTC)", "cities":"Monrovia, Reykjavik"},
        {"country":"Gibraltar", "short":"GI", "long":"W. Europe Standard Time", "value":"(UTC+01:00)", "cities":"Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna"},
        {"country":"Greece", "short":"GR", "long":"GTB Standard Time", "value":"(UTC+02:00)", "cities":"Athens, Bucharest"},
        {"country":"Greenland", "short":"GL", "long":"Greenland Standard Time", "value":"(UTC-03:00)", "cities":"Greenland"},
        {"country":"Grenada", "short":"GD", "long":"SA Western Standard Time", "value":"(UTC-04:00)", "cities":"Georgetown, La Paz, Manaus, San Juan"},
        {"country":"Guadeloupe", "short":"GP", "long":"SA Western Standard Time", "value":"(UTC-04:00)", "cities":"Georgetown, La Paz, Manaus, San Juan"},
        {"country":"Guam", "short":"GU", "long":"West Pacific Standard Time", "value":"(UTC+10:00)", "cities":"Guam, Port Moresby"},
        {"country":"Guatemala", "short":"GT", "long":"Central America Standard Time", "value":"(UTC-06:00)", "cities":"Central America"},
        {"country":"Guernsey", "short":"GG", "long":"GMT Standard Time", "value":"(UTC)", "cities":"Dublin, Edinburgh, Lisbon, London"},
        {"country":"Guinea", "short":"GN", "long":"Greenwich Standard Time", "value":"(UTC)", "cities":"Monrovia, Reykjavik"},
        {"country":"Guinea-Bissau", "short":"GW", "long":"Greenwich Standard Time", "value":"(UTC)", "cities":"Monrovia, Reykjavik"},
        {"country":"Guyana", "short":"GY", "long":"SA Western Standard Time", "value":"(UTC-04:00)", "cities":"Georgetown, La Paz, Manaus, San Juan"},
        {"country":"Haiti", "short":"HT", "long":"Eastern Standard Time", "value":"(UTC-05:00)", "cities":"Eastern Time (US & Canada)"},
        {"country":"Heard Island and McDonald Islands", "short":"HM", "long":"Mauritius Standard Time", "value":"(UTC+04:00)", "cities":"Port Louis"},
        {"country":"Honduras", "short":"HN", "long":"Central America Standard Time", "value":"(UTC-06:00)", "cities":"Central America"},
        {"country":"Hong Kong SAR", "short":"HK", "long":"China Standard Time", "value":"(UTC+08:00)", "cities":"Beijing, Chongqing, Hong Kong SAR, Urumqi"},
        {"country":"Hungary", "short":"HU", "long":"Central Europe Standard Time", "value":"(UTC+01:00)", "cities":"Belgrade, Bratislava, Budapest, Ljubljana, Prague"},
        {"country":"Iceland", "short":"IS", "long":"Greenwich Standard Time", "value":"(UTC)", "cities":"Monrovia, Reykjavik"},
        {"country":"India", "short":"IN", "long":"India Standard Time", "value":"(UTC+05:30)", "cities":"Chennai, Kolkata, Mumbai, New Delhi"},
        {"country":"Indonesia", "short":"ID", "long":"SE Asia Standard Time", "value":"(UTC+07:00)", "cities":"Bangkok, Hanoi, Jakarta"},
        {"country":"Iran", "short":"IR", "long":"Iran Standard Time", "value":"(UTC+03:30)", "cities":"Tehran"},
        {"country":"Iraq", "short":"IQ", "long":"Arabic Standard Time", "value":"(UTC+03:00)", "cities":"Baghdad"},
        {"country":"Ireland", "short":"IE", "long":"GMT Standard Time", "value":"(UTC)", "cities":"Dublin, Edinburgh, Lisbon, London"},
        {"country":"Israel", "short":"IL", "long":"Israel Standard Time", "value":"(UTC+02:00)", "cities":"Jerusalem"},
        {"country":"Italy", "short":"IT", "long":"W. Europe Standard Time", "value":"(UTC+01:00)", "cities":"Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna"},
        {"country":"Jamaica", "short":"JM", "long":"SA Pacific Standard Time", "value":"(UTC-05:00)", "cities":"Bogota, Lima, Quito, Rio Branco"},
        {"country":"Jan Mayen", "short":"SJ", "long":"W. Europe Standard Time", "value":"(UTC+01:00)", "cities":"Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna"},
        {"country":"Japan", "short":"JP", "long":"Tokyo Standard Time", "value":"(UTC+09:00)", "cities":"Osaka, Sapporo, Tokyo"},
        {"country":"Jersey", "short":"JE", "long":"GMT Standard Time", "value":"(UTC)", "cities":"Dublin, Edinburgh, Lisbon, London"},
        {"country":"Jordan", "short":"JO", "long":"Jordan Standard Time", "value":"(UTC+02:00)", "cities":"Amman"},
        {"country":"Kazakhstan", "short":"KZ", "long":"Central Asia Standard Time", "value":"(UTC+06:00)", "cities":"Astana"},
        {"country":"Kenya", "short":"KE", "long":"E. Africa Standard Time", "value":"(UTC+03:00)", "cities":"Nairobi"},
        {"country":"Kiribati", "short":"KI", "long":"UTC+12", "value":"(UTC+12:00)", "cities":"Coordinated Universal Time+12"},
        {"country":"Korea", "short":"KR", "long":"Korea Standard Time", "value":"(UTC+09:00)", "cities":"Seoul"},
        {"country":"Kosovo", "short":"XK", "long":"Central European Standard Time", "value":"(UTC+01:00)", "cities":"Sarajevo, Skopje, Warsaw, Zagreb"},
        {"country":"Kuwait", "short":"KW", "long":"Arab Standard Time", "value":"(UTC+03:00)", "cities":"Kuwait, Riyadh"},
        {"country":"Kyrgyzstan", "short":"KG", "long":"Central Asia Standard Time", "value":"(UTC+06:00)", "cities":"Astana"},
        {"country":"Laos", "short":"LA", "long":"SE Asia Standard Time", "value":"(UTC+07:00)", "cities":"Bangkok, Hanoi, Jakarta"},
        {"country":"Latvia", "short":"LV", "long":"FLE Standard Time", "value":"(UTC+02:00)", "cities":"Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius"},
        {"country":"Lebanon", "short":"LB", "long":"Middle East Standard Time", "value":"(UTC+02:00)", "cities":"Beirut"},
        {"country":"Lesotho", "short":"LS", "long":"South Africa Standard Time", "value":"(UTC+02:00)", "cities":"Harare, Pretoria"},
        {"country":"Liberia", "short":"LR", "long":"Greenwich Standard Time", "value":"(UTC)", "cities":"Monrovia, Reykjavik"},
        {"country":"Libya", "short":"LY", "long":"E. Europe Standard Time", "value":"(UTC+02:00)", "cities":"E. Europe"},
        {"country":"Liechtenstein", "short":"LI", "long":"W. Europe Standard Time", "value":"(UTC+01:00)", "cities":"Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna"},
        {"country":"Lithuania", "short":"LT", "long":"FLE Standard Time", "value":"(UTC+02:00)", "cities":"Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius"},
        {"country":"Luxembourg", "short":"LU", "long":"W. Europe Standard Time", "value":"(UTC+01:00)", "cities":"Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna"},
        {"country":"Macao SAR", "short":"MO", "long":"China Standard Time", "value":"(UTC+08:00)", "cities":"Beijing, Chongqing, Hong Kong SAR, Urumqi"},
        {"country":"Macedonia, Former Yugoslav Republic of", "short":"MK", "long":"Central European Standard Time", "value":"(UTC+01:00)", "cities":"Sarajevo, Skopje, Warsaw, Zagreb"},
        {"country":"Madagascar", "short":"MG", "long":"E. Africa Standard Time", "value":"(UTC+03:00)", "cities":"Nairobi"},
        {"country":"Malawi", "short":"MW", "long":"South Africa Standard Time", "value":"(UTC+02:00)", "cities":"Harare, Pretoria"},
        {"country":"Malaysia", "short":"MY", "long":"Singapore Standard Time", "value":"(UTC+08:00)", "cities":"Kuala Lumpur, Singapore"},
        {"country":"Maldives", "short":"MV", "long":"West Asia Standard Time", "value":"(UTC+05:00)", "cities":"Ashgabat, Tashkent"},
        {"country":"Mali", "short":"ML", "long":"Greenwich Standard Time", "value":"(UTC)", "cities":"Monrovia, Reykjavik"},
        {"country":"Malta", "short":"MT", "long":"W. Europe Standard Time", "value":"(UTC+01:00)", "cities":"Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna"},
        {"country":"Man, Isle of", "short":"IM", "long":"GMT Standard Time", "value":"(UTC)", "cities":"Dublin, Edinburgh, Lisbon, London"},
        {"country":"Marshall Islands", "short":"MH", "long":"UTC+12", "value":"(UTC+12:00)", "cities":"Coordinated Universal Time+12"},
        {"country":"Martinique", "short":"MQ", "long":"SA Western Standard Time", "value":"(UTC-04:00)", "cities":"Georgetown, La Paz, Manaus, San Juan"},
        {"country":"Mauritania", "short":"MR", "long":"Greenwich Standard Time", "value":"(UTC)", "cities":"Monrovia, Reykjavik"},
        {"country":"Mauritius", "short":"MU", "long":"Mauritius Standard Time", "value":"(UTC+04:00)", "cities":"Port Louis"},
        {"country":"Mayotte", "short":"YT", "long":"E. Africa Standard Time", "value":"(UTC+03:00)", "cities":"Nairobi"},
        {"country":"Mexico", "short":"MX", "long":"Central Standard Time (Mexico)", "value":"(UTC-06:00)", "cities":"Guadalajara, Mexico City, Monterrey"},
        {"country":"Micronesia", "short":"FM", "long":"West Pacific Standard Time", "value":"(UTC+10:00)", "cities":"Guam, Port Moresby"},
        {"country":"Moldova", "short":"MD", "long":"GTB Standard Time", "value":"(UTC+02:00)", "cities":"Athens, Bucharest"},
        {"country":"Monaco", "short":"MC", "long":"W. Europe Standard Time", "value":"(UTC+01:00)", "cities":"Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna"},
        {"country":"Mongolia", "short":"MN", "long":"Ulaanbaatar Standard Time", "value":"(UTC+08:00)", "cities":"Ulaanbaatar"},
        {"country":"Montenegro", "short":"ME", "long":"Central European Standard Time", "value":"(UTC+01:00)", "cities":"Sarajevo, Skopje, Warsaw, Zagreb"},
        {"country":"Montserrat", "short":"MS", "long":"SA Western Standard Time", "value":"(UTC-04:00)", "cities":"Georgetown, La Paz, Manaus, San Juan"},
        {"country":"Morocco", "short":"MA", "long":"Morocco Standard Time", "value":"(UTC)", "cities":"Casablanca"},
        {"country":"Mozambique", "short":"MZ", "long":"South Africa Standard Time", "value":"(UTC+02:00)", "cities":"Harare, Pretoria"},
        {"country":"Myanmar", "short":"MM", "long":"Myanmar Standard Time", "value":"(UTC+06:30)", "cities":"Yangon (Rangoon)"},
        {"country":"Namibia", "short":"NA", "long":"Namibia Standard Time", "value":"(UTC+01:00)", "cities":"Windhoek"},
        {"country":"Nauru", "short":"NR", "long":"UTC+12", "value":"(UTC+12:00)", "cities":"Coordinated Universal Time+12"},
        {"country":"Nepal", "short":"NP", "long":"Nepal Standard Time", "value":"(UTC+05:45)", "cities":"Kathmandu"},
        {"country":"Netherlands", "short":"NL", "long":"W. Europe Standard Time", "value":"(UTC+01:00)", "cities":"Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna"},
        {"country":"New Caledonia", "short":"NC", "long":"Central Pacific Standard Time", "value":"(UTC+11:00)", "cities":"Solomon Is., New Caledonia"},
        {"country":"New Zealand", "short":"NZ", "long":"New Zealand Standard Time", "value":"(UTC+12:00)", "cities":"Auckland, Wellington"},
        {"country":"Nicaragua", "short":"NI", "long":"Central America Standard Time", "value":"(UTC-06:00)", "cities":"Central America"},
        {"country":"Niger", "short":"NE", "long":"W. Central Africa Standard Time", "value":"(UTC+01:00)", "cities":"West Central Africa"},
        {"country":"Nigeria", "short":"NG", "long":"W. Central Africa Standard Time", "value":"(UTC+01:00)", "cities":"West Central Africa"},
        {"country":"Niue", "short":"NU", "long":"UTC-11", "value":"(UTC-11:00)", "cities":"Coordinated Universal Time-11"},
        {"country":"Norfolk Island", "short":"NF", "long":"Central Pacific Standard Time", "value":"(UTC+11:00)", "cities":"Solomon Is., New Caledonia"},
        {"country":"North Korea", "short":"KP", "long":"Korea Standard Time", "value":"(UTC+09:00)", "cities":"Seoul"},
        {"country":"Northern Mariana Islands", "short":"MP", "long":"West Pacific Standard Time", "value":"(UTC+10:00)", "cities":"Guam, Port Moresby"},
        {"country":"Norway", "short":"NO", "long":"W. Europe Standard Time", "value":"(UTC+01:00)", "cities":"Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna"},
        {"country":"Oman", "short":"OM", "long":"Arabian Standard Time", "value":"(UTC+04:00)", "cities":"Abu Dhabi, Muscat"},
        {"country":"Pakistan", "short":"PK", "long":"Pakistan Standard Time", "value":"(UTC+05:00)", "cities":"Islamabad, Karachi"},
        {"country":"Palau", "short":"PW", "long":"Tokyo Standard Time", "value":"(UTC+09:00)", "cities":"Osaka, Sapporo, Tokyo"},
        {"country":"Palestinian Authority", "short":"PS", "long":"Egypt Standard Time", "value":"(UTC+02:00)", "cities":"Cairo"},
        {"country":"Panama", "short":"PA", "long":"SA Pacific Standard Time", "value":"(UTC-05:00)", "cities":"Bogota, Lima, Quito, Rio Branco"},
        {"country":"Papua New Guinea", "short":"PG", "long":"West Pacific Standard Time", "value":"(UTC+10:00)", "cities":"Guam, Port Moresby"},
        {"country":"Paraguay", "short":"PY", "long":"Paraguay Standard Time", "value":"(UTC-04:00)", "cities":"Asuncion"},
        {"country":"Peru", "short":"PE", "long":"SA Pacific Standard Time", "value":"(UTC-05:00)", "cities":"Bogota, Lima, Quito, Rio Branco"},
        {"country":"Philippines", "short":"PH", "long":"Singapore Standard Time", "value":"(UTC+08:00)", "cities":"Kuala Lumpur, Singapore"},
        {"country":"Pitcairn Islands", "short":"PN", "long":"Pacific Standard Time", "value":"(UTC-08:00)", "cities":"Pacific Time (US & Canada)"},
        {"country":"Poland", "short":"PL", "long":"Central European Standard Time", "value":"(UTC+01:00)", "cities":"Sarajevo, Skopje, Warsaw, Zagreb"},
        {"country":"Portugal", "short":"PT", "long":"GMT Standard Time", "value":"(UTC)", "cities":"Dublin, Edinburgh, Lisbon, London"},
        {"country":"Puerto Rico", "short":"PR", "long":"SA Western Standard Time", "value":"(UTC-04:00)", "cities":"Georgetown, La Paz, Manaus, San Juan"},
        {"country":"Qatar", "short":"QA", "long":"Arab Standard Time", "value":"(UTC+03:00)", "cities":"Kuwait, Riyadh"},
        {"country":"Reunion", "short":"RE", "long":"Mauritius Standard Time", "value":"(UTC+04:00)", "cities":"Port Louis"},
        {"country":"Romania", "short":"RO", "long":"GTB Standard Time", "value":"(UTC+02:00)", "cities":"Athens, Bucharest"},
        {"country":"Russia", "short":"RU", "long":"Russian Standard Time", "value":"(UTC+03:00)", "cities":"Moscow, St. Petersburg, Volgograd (RTZ 2)"},
        {"country":"Rwanda", "short":"RW", "long":"South Africa Standard Time", "value":"(UTC+02:00)", "cities":"Harare, Pretoria"},
        {"country":"Saint Barthélemy", "short":"BL", "long":"SA Western Standard Time", "value":"(UTC-04:00)", "cities":"Georgetown, La Paz, Manaus, San Juan"},
        {"country":"Saint Helena, Ascension and Tristan da Cunha", "short":"SH", "long":"Greenwich Standard Time", "value":"(UTC)", "cities":"Monrovia, Reykjavik"},
        {"country":"Saint Kitts and Nevis", "short":"KN", "long":"SA Western Standard Time", "value":"(UTC-04:00)", "cities":"Georgetown, La Paz, Manaus, San Juan"},
        {"country":"Saint Lucia", "short":"LC", "long":"SA Western Standard Time", "value":"(UTC-04:00)", "cities":"Georgetown, La Paz, Manaus, San Juan"},
        {"country":"Saint Martin (French part)", "short":"MF", "long":"SA Western Standard Time", "value":"(UTC-04:00)", "cities":"Georgetown, La Paz, Manaus, San Juan"},
        {"country":"Saint Pierre and Miquelon", "short":"PM", "long":"Greenland Standard Time", "value":"(UTC-03:00)", "cities":"Greenland"},
        {"country":"Saint Vincent and the Grenadines", "short":"VC", "long":"SA Western Standard Time", "value":"(UTC-04:00)", "cities":"Georgetown, La Paz, Manaus, San Juan"},
        {"country":"Samoa", "short":"WS", "long":"Samoa Standard Time", "value":"(UTC+13:00)", "cities":"Samoa"},
        {"country":"San Marino", "short":"SM", "long":"W. Europe Standard Time", "value":"(UTC+01:00)", "cities":"Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna"},
        {"country":"São Tomé and Príncipe", "short":"ST", "long":"Greenwich Standard Time", "value":"(UTC)", "cities":"Monrovia, Reykjavik"},
        {"country":"Saudi Arabia", "short":"SA", "long":"Arab Standard Time", "value":"(UTC+03:00)", "cities":"Kuwait, Riyadh"},
        {"country":"Senegal", "short":"SN", "long":"Greenwich Standard Time", "value":"(UTC)", "cities":"Monrovia, Reykjavik"},
        {"country":"Serbia", "short":"RS", "long":"Central Europe Standard Time", "value":"(UTC+01:00)", "cities":"Belgrade, Bratislava, Budapest, Ljubljana, Prague"},
        {"country":"Seychelles", "short":"SC", "long":"Mauritius Standard Time", "value":"(UTC+04:00)", "cities":"Port Louis"},
        {"country":"Sierra Leone", "short":"SL", "long":"Greenwich Standard Time", "value":"(UTC)", "cities":"Monrovia, Reykjavik"},
        {"country":"Singapore", "short":"SG", "long":"Singapore Standard Time", "value":"(UTC+08:00)", "cities":"Kuala Lumpur, Singapore"},
        {"country":"Sint Maarten (Dutch part)", "short":"SX", "long":"SA Western Standard Time", "value":"(UTC-04:00)", "cities":"Georgetown, La Paz, Manaus, San Juan"},
        {"country":"Slovakia", "short":"SK", "long":"Central Europe Standard Time", "value":"(UTC+01:00)", "cities":"Belgrade, Bratislava, Budapest, Ljubljana, Prague"},
        {"country":"Slovenia", "short":"SI", "long":"Central Europe Standard Time", "value":"(UTC+01:00)", "cities":"Belgrade, Bratislava, Budapest, Ljubljana, Prague"},
        {"country":"Solomon Islands", "short":"SB", "long":"Central Pacific Standard Time", "value":"(UTC+11:00)", "cities":"Solomon Is., New Caledonia"},
        {"country":"Somalia", "short":"SO", "long":"E. Africa Standard Time", "value":"(UTC+03:00)", "cities":"Nairobi"},
        {"country":"South Africa", "short":"ZA", "long":"South Africa Standard Time", "value":"(UTC+02:00)", "cities":"Harare, Pretoria"},
        {"country":"South Georgia and the South Sandwich Islands", "short":"GS", "long":"UTC-02", "value":"(UTC-02:00)", "cities":"Coordinated Universal Time-02"},
        {"country":"South Sudan", "short":"SS", "long":"E. Africa Standard Time", "value":"(UTC+03:00)", "cities":"Nairobi"},
        {"country":"Spain", "short":"ES", "long":"Romance Standard Time", "value":"(UTC+01:00)", "cities":"Brussels, Copenhagen, Madrid, Paris"},
        {"country":"Sri Lanka", "short":"LK", "long":"Sri Lanka Standard Time", "value":"(UTC+05:30)", "cities":"Sri Jayawardenepura"},
        {"country":"Sudan", "short":"SD", "long":"E. Africa Standard Time", "value":"(UTC+03:00)", "cities":"Nairobi"},
        {"country":"Suriname", "short":"SR", "long":"SA Eastern Standard Time", "value":"(UTC-03:00)", "cities":"Cayenne, Fortaleza"},
        {"country":"Svalbard", "short":"SJ", "long":"W. Europe Standard Time", "value":"(UTC+01:00)", "cities":"Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna"},
        {"country":"Swaziland", "short":"SZ", "long":"South Africa Standard Time", "value":"(UTC+02:00)", "cities":"Harare, Pretoria"},
        {"country":"Sweden", "short":"SE", "long":"W. Europe Standard Time", "value":"(UTC+01:00)", "cities":"Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna"},
        {"country":"Switzerland", "short":"CH", "long":"W. Europe Standard Time", "value":"(UTC+01:00)", "cities":"Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna"},
        {"country":"Syria", "short":"SY", "long":"Syria Standard Time", "value":"(UTC+02:00)", "cities":"Damascus"},
        {"country":"Taiwan", "short":"TW", "long":"Taipei Standard Time", "value":"(UTC+08:00)", "cities":"Taipei"},
        {"country":"Tajikistan", "short":"TJ", "long":"West Asia Standard Time", "value":"(UTC+05:00)", "cities":"Ashgabat, Tashkent"},
        {"country":"Tanzania", "short":"TZ", "long":"E. Africa Standard Time", "value":"(UTC+03:00)", "cities":"Nairobi"},
        {"country":"Thailand", "short":"TH", "long":"SE Asia Standard Time", "value":"(UTC+07:00)", "cities":"Bangkok, Hanoi, Jakarta"},
        {"country":"Togo", "short":"TG", "long":"Greenwich Standard Time", "value":"(UTC)", "cities":"Monrovia, Reykjavik"},
        {"country":"Tokelau", "short":"TK", "long":"Tonga Standard Time", "value":"(UTC+13:00)", "cities":"Nuku'alofa"},
        {"country":"Tonga", "short":"TO", "long":"Tonga Standard Time", "value":"(UTC+13:00)", "cities":"Nuku'alofa"},
        {"country":"Trinidad and Tobago", "short":"TT", "long":"SA Western Standard Time", "value":"(UTC-04:00)", "cities":"Georgetown, La Paz, Manaus, San Juan"},
        {"country":"Tunisia", "short":"TN", "long":"W. Central Africa Standard Time", "value":"(UTC+01:00)", "cities":"West Central Africa"},
        {"country":"Turkey", "short":"TR", "long":"Turkey Standard Time", "value":"(UTC+02:00)", "cities":"Istanbul"},
        {"country":"Turkmenistan", "short":"TM", "long":"West Asia Standard Time", "value":"(UTC+05:00)", "cities":"Ashgabat, Tashkent"},
        {"country":"Turks and Caicos Islands", "short":"TC", "long":"Eastern Standard Time", "value":"(UTC-05:00)", "cities":"Eastern Time (US & Canada)"},
        {"country":"Tuvalu", "short":"TV", "long":"UTC+12", "value":"(UTC+12:00)", "cities":"Coordinated Universal Time+12"},
        {"country":"U.S. Minor Outlying Islands", "short":"UM", "long":"UTC-11", "value":"(UTC-11:00)", "cities":"Coordinated Universal Time-11"},
        {"country":"Uganda", "short":"UG", "long":"E. Africa Standard Time", "value":"(UTC+03:00)", "cities":"Nairobi"},
        {"country":"Ukraine", "short":"UA", "long":"FLE Standard Time", "value":"(UTC+02:00)", "cities":"Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius"},
        {"country":"United Arab Emirates", "short":"AE", "long":"Arabian Standard Time", "value":"(UTC+04:00)", "cities":"Abu Dhabi, Muscat"},
        {"country":"United Kingdom", "short":"GB", "long":"GMT Standard Time", "value":"(UTC)", "cities":"Dublin, Edinburgh, Lisbon, London"},
        {"country":"United States", "short":"US", "long":"Mountain Standard Time", "value":"(UTC-07:00)", "cities":"Mountain Time (US & Canada)"},
        {"country":"United States", "short":"US", "long":"Pacific Standard Time", "value":"(UTC-08:00)", "cities":"Pacific Time (US & Canada)"},
        {"country":"Uruguay", "short":"UY", "long":"Montevideo Standard Time", "value":"(UTC-03:00)", "cities":"Montevideo"},
        {"country":"Uzbekistan", "short":"UZ", "long":"West Asia Standard Time", "value":"(UTC+05:00)", "cities":"Ashgabat, Tashkent"},
        {"country":"Vanuatu", "short":"VU", "long":"Central Pacific Standard Time", "value":"(UTC+11:00)", "cities":"Solomon Is., New Caledonia"},
        {"country":"Vatican City", "short":"VA", "long":"W. Europe Standard Time", "value":"(UTC+01:00)", "cities":"Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna"},
        {"country":"Vietnam", "short":"VN", "long":"SE Asia Standard Time", "value":"(UTC+07:00)", "cities":"Bangkok, Hanoi, Jakarta"},
        {"country":"Virgin Islands, U.S.", "short":"VI", "long":"SA Western Standard Time", "value":"(UTC-04:00)", "cities":"Georgetown, La Paz, Manaus, San Juan"},
        {"country":"Virgin Islands, British", "short":"VG", "long":"SA Western Standard Time", "value":"(UTC-04:00)", "cities":"Georgetown, La Paz, Manaus, San Juan"},
        {"country":"Wallis and Futuna", "short":"WF", "long":"UTC+12", "value":"(UTC+12:00)", "cities":"Coordinated Universal Time+12"},
        {"country":"Yemen", "short":"YE", "long":"Arab Standard Time", "value":"(UTC+03:00)", "cities":"Kuwait, Riyadh"},
        {"country":"Zambia", "short":"ZM", "long":"South Africa Standard Time", "value":"(UTC+02:00)", "cities":"Harare, Pretoria"},
        {"country":"Zimbabwe", "short":"ZW", "long":"South Africa Standard Time", "value":"(UTC+02:00)", "cities":"Harare, Pretoria"}]